### ISSUE TITLE
Portlet Administrator UI modify properties with wrong charset

### ISSUE THREAD

**Issue by jgribonvald** [Jasig/uPortal#1321]
**Describe the bug**

The UI doesn't save portlet information with the good charset see animated gif from @ChristianMurphy  bellow (reproduction test).
The problems is only in the UI as XML files doesn't have this problem. Also this problem didn't exist before, at least in uP4.3.

**To Reproduce**
![example-with-accent-marks](https://user-images.githubusercontent.com/1597283/44867690-da222280-ac88-11e8-95a3-ffff08ac6bf8.gif)

**Expected behavior**
Saving with UI cause bad charset encoding on UTF-8 chars like [é à ...]

**Platform:**
 - uPortal Version: uPortal 5.2.2
 - Browser: Chrome, Firefox

**Comment by ChristianMurphy** [comment]
Resolved in #1321
