### ISSUE TITLE
A "health check" endpoint to enable deploying on cloud servers

### ISSUE THREAD

**Issue by laurenra7** [Jasig/uPortal#1331]
**Is your feature request related to a problem? Please describe.**
To deploy to cloud servers, for example Amazon Web Services (AWS), a load balancer requires an endpoint on the application server that it can ping at regular intervals.

**Describe the solution you'd like**
As a developer and administrator, I want a simple health check endpoint, for example **/uPortal/health-check**, that I can provide to an AWS load balancer that it can ping every few seconds. It should be outside the uPortal security filters and other filter chains so it returns a result quickly and isn't dependent on authentication or authorization. It should just respond to HTTP GET requests and return an HTTP 200 status (OK), nothing else.

**Describe alternatives you've considered**
I considered using an existing uPortal REST API endpoint like the /api/session.json which returns a result with HTTP 200 status even if not logged in. Unfortunately, because it returns JSON, it's much more complicated to configure with the load balancer. More importantly, because it's in a filter chain, several other things must get loaded before it returns a result, which can take a lot of time (10 seconds or more) on the first ping. I tried this and the load balancer never achieved a "healthy" status because of the amount of time it took for that first ping. For these reasons, a simple JSP page would also be impractical. I looked at the health check strategy for the approved Docker container in the uPortal-start project but it would not work for this.

**Additional context**
I'm only familiar with AWS, but a health check is a common need for load balancers in general. It seems this would be beneficial for others who want to deploy a cluster of Tomcat servers running uPortal, hosted on their own servers or on cloud servers. The health check facilitates automatically spinning up new servers if there is a problem with an existing one, simplifying administration of the servers.

**Comment by ChristianMurphy** [comment]
Added in #1333, will be a part of uPortal 5.3.0
