### ISSUE TITLE
Accessibility issue -- skipnav  includes role='button' (but shouldn't?)

### ISSUE THREAD

**Issue by drewwills** [Jasig/uPortal#1353]
## Describe the bug
This item was reported by a long-standing uPortal community institution that performed an accessibility audit:

  - Skip link includes `role="button"` but shouldn't (semantically not a button);  https://github.com/Jasig/uPortal/blob/master/uPortal-webapp/src/main/resources/layout/theme/respondr/navigation.xsl#L375

Thoughts @ChristianMurphy, @cousquer, @asgrant, @jgribonvald?

**Comment by ChristianMurphy** [comment]
> A link widget provides an interactive reference to a resource. The target resource can be either external or local, i.e., either outside or within the current page or application.

https://www.w3.org/TR/wai-aria-practices/#link

> A button is a widget that enables users to trigger an action or event, such as submitting a form, opening a dialog, canceling an action, or performing a delete operation. A common convention for informing users that a button launches a dialog is to append "…" (ellipsis) to the button label, e.g., "Save as…". 

https://www.w3.org/TR/wai-aria-practices/#button

---

Skip to content jumps to a location within the page.
Seems like link may be a better fit.

**Comment by cousquer** [comment]
If it goes somewhere, use a link `<a>`, if it does something, use a `<button>`.

**Comment by cousquer** [comment]
resolved in #1509
