### ISSUE TITLE
Login failure with uPortal 5.3.0 + CAS

### ISSUE THREAD

**Issue by jonathanmtran** [Jasig/uPortal#1372]
**Describe the bug**

Upgrading to uPortal 5.3.0, I'm unable to successfully log in using CAS authentication

Using the bundled CAS with uPortal-start, I increased the logging level and saw the following
```xml
<cas:serviceResponse xmlns:cas='http://www.yale.edu/tp/cas'>
        <cas:authenticationFailure code='INVALID_SERVICE'>
                ticket &#039;ST-1-JTrOtMpLdXOFzIcfnp7J-cas01.example.org&#039; does not match supplied service.  The original service was &#039;http://localhost:8080/uPortal/Login&#039; and the supplied service
was &#039;http://localhost:8080 /uPortal/Login&#039;.
        </cas:authenticationFailure>
</cas:serviceResponse>
```
It seems that there is a whitespace after `http://localhost:8080` but I can't seem to find where the whitepace is coming from

**To Reproduce**
1. Deploy HEAD of uPortal-start
2. Attempt to log in

**Platform:**
 - uPortal Version: uPortal 5.3.0

**Comment by jonathanmtran** [comment]
I did increase the logging level of `org.apereo.portal.url` and the URLs are are being returned correctly from what I can see

```
DEBUG [http-nio-8080-exec-14-guest] o.a.p.u.UrlMultiServerNameCustomizer 2018-10-11 18:28:29,810 - Modifying Url Domain from [http://localhost:8080/cas/login?service=http://_CURRENT_SERVER_NAME_/uPortal/Login] to [http://localhost:8080/cas/login?service=http://localhost:8080/uPortal/Login]
DEBUG [http-nio-8080-exec-14-guest] o.a.p.url.UrlAuthCustomizerRegistry 2018-10-11 18:28:29,810 - The url returned after customization is http://localhost:8080/cas/login?service=http://localhost:8080/uPortal/Login
```

**Comment by jonathanmtran** [comment]
Ah.

In securityContext.xml, serverName is `${portal.allServerNames}`
https://github.com/Jasig/uPortal/blob/faa1e0f0e63a409039e7b49ae71b0f920d53ba19/uPortal-webapp/src/main/resources/properties/contexts/securityContext.xml#L121

If I override `portal.allServerNames` to be just `${portal.server}`, login succeeds
https://github.com/Jasig/uPortal/blob/faa1e0f0e63a409039e7b49ae71b0f920d53ba19/uPortal-webapp/src/main/resources/properties/security.properties#L41-L48

Out of the box, `portal.OtherServers` is empty and we end up with `portal.allServerNames=${portal.server}<whitepsace>`

So it appears that `Cas20ProxyReceivingTicketValidationFilter` doesn't remove trailing whitespace(s) ...

Maybe moving forward, the default value of `portal.allServerNames` should be `portal.server` and should be overridden via `${portal.home}/uPortal.properties`. Would that still work for @jgribonvald's use case ?

**Comment by jgribonvald** [comment]
Sorry, too much things to manage today :dizzy_face:

Yes I'm agree with that, in all case $portal.allServerNames could be overriden from PORTAL_HOME

**Comment by drewwills** [comment]
Folks,

    Maybe moving forward, the default value of portal.allServerNames should be ${portal.server}
    and if the need arises, it portal.allServerNames could be overridden via
    ${portal.home}/uPortal.properties.

In addition to what we've already discussed, my gut tells me that we should eliminate the `portal.otherServers` altogether, since it's not necessary.

In this case -- when you want to use the new feature(s) -- instead of defining (in uPortal.properties)...

```
portal.server=portal1.my.edu
portal.otherServers=portal2.my.edu portal3.my.edu
portal.allServerNames=${portal.server} ${portal.otherServers}
```
you would simply define...

```
portal.server=portal1.my.edu
portal.allServerNames=${portal.server} portal2.my.edu portal3.my.edu
```

How does that sound?

**Comment by jonathanmtran** [comment]
Got that covered 

https://github.com/Jasig/uPortal/pull/1373/files#diff-c054f6e748f59a85048c117fe7e8221a
