### ISSUE TITLE
Deprecated code on jsTree.js

### ISSUE THREAD

**Issue by jgribonvald** [Jasig/uPortal#1379]
**Describe the bug**
Incomming problem with jsTree lib, it won't work anymore on google chrome from around march 2019.
See trace from the browser console: 

**Stacktrace**
 [Deprecation] document.registerElement is deprecated and will be removed in M73, around March 2019. Please use window.customElements.define instead. See https://www.chromestatus.com/features/4642138092470272 for more details.

**Platform:**
 - uPortal Version: All having jsTree
 - Browser : Chrome Version 70.0.3538.67 (Build officiel) (64 bits)

**Additional context**
It's only to put a warning on this incoming problem !

**Comment by ChristianMurphy** [comment]
We'll need to apply https://github.com/vakata/jstree/commit/537a32301d1f786dd2a523abf5c24e5bb0f193bc once it is released.

**Comment by drewwills** [comment]
Thanks, both of you, for your diligence.

**Comment by ChristianMurphy** [comment]
JSTree 3.3.7 is out now with the fix
