### ISSUE TITLE
Support session-less access to uPortal REST APIs based on the Authorization header (OIDC Id token)

### ISSUE THREAD

**Issue by drewwills** [Jasig/uPortal#1438]
## Summary

uPortal 5.1 and above provides a `/userinfo` endpoint through which content objects may obtain an OAuth2/OIDC Id token from the portal.  This token provides the identity, attributes, and group affiliations of the user, and it may be used to secure REST APIs.

The portal's own REST APIs, however, do not support this token.  Currently there is no way to invoke the portal's APIs except by presenting a `JSESSIONID` cookie representing an authenticated browser session.

We need to change that -- we need to provide support for other types of clients (besides JavaScript running on the portal page) to access these APIs as an authenticated user.  We need to support session-less access to uPortal REST APIs based on the portal-provided OIDC Id token in the Authorization header.

**Comment by jonathanmtran** [comment]
Initial quick testing against `api/groups` and `api/v4-3/dlm/portletRegistry.json` using curl look good. I will do additional testing and update as that progresses.
