### ISSUE TITLE
Guest user occasionally receives a portal page without a skin when using the dynamic-respondr-skin portlet

### ISSUE THREAD

**Issue by drewwills** [Jasig/uPortal#1467]
## Describe the bug

Occasionally (but typically uncommonly) unauthenticated users will start receiving a portal page that does not include the `dynamic-respondr-skin` portlet and therefore has no skin.  The affected page is completely unusable.

This issue has been encountered by several, and has been discussed more than once on the `uportal-user` list:  https://groups.google.com/a/apereo.org/forum/#!topic/uportal-user/JBy0Mp7YvG0

The issue stems from the `ThemeNameEqualsIgnoreCaseTester`.  This PAGS tester requires an active `HttpServletRequest` to function, otherwise it always returns `false` (i.e. the user is not a member of the group).  The problem is that this tester can be invoked within the Event Aggregation processes, which happen on a worker (non-request) thread.

In a typical data set (since the portlet was introduced), users receive the `dynamic-respondr-skin` portlet by virtue of their membership in the `Respondr Theme Users` group -- a PAGS group based on the `ThemeNameEqualsIgnoreCaseTester`.

Membership evaluations are cached in the portal.  When a test for membership in the `Respondr Theme Users` group for the `guest` user returns `false`, that result will be cached for a period.  During that period, real guest users will not receive the `dynamic-respondr-skin` portlet.

## How To Fix

Clearly the `ThemeNameEqualsIgnoreCaseTester` has issues, and (furthermore) we don't need it the way we did when it was introduced.  (The Universality theme has been removed.)  We should deprecate it, remove all usages of it from data sets in uPortal-start, and publish the solution in the released notes.

**Comment by drewwills** [comment]
See also https://github.com/Jasig/uPortal-start/pull/256.

**Comment by jgribonvald** [comment]
As feedback: the problem doesn't appear anymore when removing usage of the ThemeNameEqualsIgnoreCaseTester (feedback provided by 2 universities)

**Comment by drewwills** [comment]
@jgribonvald -- thanks very much for providing an update.
