### ISSUE TITLE
uportal-start failed in error - branch master

### ISSUE THREAD

**Issue by aamoussa** [Jasig/uPortal#1505]
Hello , Download the latest version of uportal using git , when trying to run the gradle command portalInit , if failed in error . Can you please help for this issue . I am doing the test of raberryPi . Here is the stacktrace . 
./gradlew portalInit
Starting a Gradle Daemon (subsequent builds will be faster)
Parallel execution is an incubating feature.
> Task :buildSrc:compileJava NO-SOURCE
> Task :buildSrc:compileGroovy
> Task :buildSrc:compileGroovy UP-TO-DATE
> Task :buildSrc:processResources UP-TO-DATE
> Task :buildSrc:classes UP-TO-DATE
> Task :buildSrc:jar UP-TO-DATE
> Task :buildSrc:assemble UP-TO-DATE
> Task :buildSrc:compileTestJava NO-SOURCE
> Task :buildSrc:compileTestGroovy NO-SOURCE
> Task :buildSrc:processTestResources NO-SOURCE
> Task :buildSrc:testClasses UP-TO-DATE
> Task :buildSrc:test NO-SOURCE
> Task :buildSrc:check UP-TO-DATE
> Task :buildSrc:build UP-TO-DATE

> Configure project :overlays:uPortal
Skipping prepareSkinResources;  no custom skin files defined in /home/pi/uPortal-start/overlays/uPortal/src/main/webapp/media/skins/respondr

 Task :tomcatInstall FAILED

> Task :overlays:basiclti-portlet:plutoAssemble
Processing archive basiclti-portlet.war into destination directory /home/pi/uPortal-start/overlays/basiclti-portlet/build/pluto with the Apache Pluto Assembler

> Task :overlays:BookmarksPortlet:war
> Task :overlays:Announcements:war

FAILURE: Build failed with an exception.

* Where:
Script '/home/pi/uPortal-start/gradle/tasks/tomcat.gradle' line: 57

* What went wrong:
Execution failed for task ':tomcatInstall'.
> Problem expanding gzip /home/pi/uPortal-start/build/tmp/tomcat/tomcat-gunziped.tar

**Comment by ChristianMurphy** [comment]
Hey @aamoussa,
uPortal and uPortal-start are both working on CI (https://travis-ci.org/Jasig/uPortal-start/builds/483572127, https://travis-ci.org/Jasig/uPortal/builds/483090087, https://ci.appveyor.com/project/drewwills/uportal/builds/21706415) and on my local setup on Ubuntu.

I suspect the issue you are experiencing is related to:

> I am doing the test of raberryPi

Gradle can be a bit of a memory hog.
Running a pared down version may work better for the Pi.

```sh
./gradlew --no-daemon --no-parallel --debug portalInit
```

The `--no-daemon` and `--no-parallel` options will limit memory usage, `--debug` will provide better error logging if the issue persists.

**Comment by aamoussa** [comment]
Thanks @ChristianMurphy  , I run the given cmd it look like runing to init the portal . but the build failed in error for memory leak . I am trying on debian desktop and lets you know if I am have some error . Thanks you for helps .

**Comment by aamoussa** [comment]
I run into error on debian dekstop machine . may be problem with open-jdk . should I install oracle-jdk ? 
> Task :overlays:cas:compileJava FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':overlays:cas:compileJava'.
> Could not find tools.jar. Please check that /usr/lib/jvm/java-8-openjdk-amd64 contains a valid JDK installation.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 8m 14s
30 actionable tasks: 21 executed, 9 up-to-date

**Comment by ChristianMurphy** [comment]
Check to make sure `JAVA_HOME` has been set on the path.
See: https://stackoverflow.com/questions/17287542/setting-java-home-path-on-ubuntu and https://serverfault.com/questions/143786/how-to-determine-java-home-on-debian-ubuntu

**Comment by aamoussa** [comment]
I google the error and found lots of related question  thanks ,

**Comment by aamoussa** [comment]
I finally get it running . Thanks @ChristianMurphy  for help .
