### ISSUE TITLE
Create a Direct URL item for the Portlet Options menu

### ISSUE THREAD

**Issue by cbeach47** [Jasig/uPortal#1592]
There is a desire to have the Portlet Options menu support a 'Direct URL' action.

When a user clicks on the 'Direct URL' action, a modal dialog should popup with the full URL.

If time, having a 'copy to clipboard' button in the dialog would be nice.

**Comment by drewwills** [comment]
Thanks for creating this ticket :+1:

**Comment by cbeach47** [comment]
The link:

![image](https://user-images.githubusercontent.com/28629296/54000302-80edec80-410c-11e9-91ba-981f903b4dfa.png)

Launches the modal:
![image](https://user-images.githubusercontent.com/28629296/54000331-96fbad00-410c-11e9-9fb6-94dc7b3fa39b.png)

Still need to finish getting the proper domain/protocol.

**Comment by drewwills** [comment]
@cbeach47 -- that's a good start :+1: 

It looks like we still nee schema & port, plus a few punctuation characters.
