### ISSUE TITLE
Aggregation doesn't aggregate past "now"

### ISSUE THREAD

**Issue by jonathanmtran** [Jasig/uPortal#1691]
**Describe the bug**
Aggregation doesn't appear to aggregate past "now". The numbers in the Portal Activity portlet for "today" and "yesterday" remain at 0 and there are no search terms.

**To Reproduce**
1. Log in, browse, etc to generate events
2. Wait at least 5 minutes
3. Review Portal Activity portlet

**Expected behavior**
Updated numbers and search terms

**Comment by bjagg** [comment]
https://github.com/Jasig/uPortal/blob/master/uPortal-webapp/src/main/webapp/WEB-INF/jsp/Activity/activity.jsp

**Comment by bjagg** [comment]
https://github.com/Jasig/uPortal/blob/fb42cf9525325f6fea234bf9593910e0ef45d51f/uPortal-portlets/src/main/java/org/apereo/portal/portlets/activity/ActivityController.java

**Comment by ChristianMurphy** [comment]
resolved in #1788
