### ISSUE TITLE
Upgrade jQuery to 1.12.4

### ISSUE THREAD

**Issue by allanjackson** [Jasig/uPortal#1719]
jQuery 1.11.x includes a bug that causes issues for portlets that try to "sub" uPortal's jQuery. https://github.com/jquery/jquery-migrate/issues/84

jQuery 1.12.x includes a fix for this bug (as well as performance improvements). There are no known breaking changes for this version of jQuery. https://blog.jquery.com/2016/01/08/jquery-2-2-and-1-12-released/

**Comment by ChristianMurphy** [comment]
updated in #1720
