### ISSUE TITLE
Fix check for session max inactive

### ISSUE THREAD

**Issue by bjagg** [Jasig/uPortal#1742]
**Is your feature request related to a problem? Please describe.**
For installations that use a separate front-end, there needs to be a way to "touch" the user session to avoid timing out.

**Describe the solution you'd like**
Implement this as an API call that checks the user's currently configured session duration and return the value as JSON.

**Describe alternatives you've considered**
A more ambitious alternative is to have all (most?) API endpoints check if there is a session cookie and update session. "Touching a session" is not currently implemented in the related Tomcat spec.

**Additional context**
Again, this will help those front-ends that heavily leverage APIs

**Comment by ChristianMurphy** [comment]
> Implement this as an API call that checks the user's currently configured session duration and return the value as JSON

Isn't this information provided in the jwt from `/user-info`?

> there needs to be a way to "touch" the user session to avoid timing out

Does `/user-info` support OIDC refresh token handling?

**Comment by mrapczynski** [comment]
Just adding some $0.02 here, I'm wondering if this would be better implemented both as an API, and as a type of servlet filter that is applied to the existing API routes. To provide of example of how this could work, see here: https://github.com/expressjs/session#rolling. Sorry for referencing a different language, I'm just pointing out the concept of the rolling session.

What's missing from the API routes is refreshing the session timeout. In the case of a rich frontend served only once from the layout engine (i.e. a Vue or React SPA), then the APIs need to take on the important role of keeping the session alive. Testing using `/uPortal/api/session.json` suggested that the session timeout was not being refreshed via API calls, but only layout renders. This is especially true if there are group based rules that set different timeouts for different slices of the user population based on attributes.

**Comment by bjagg** [comment]
I'll pull a WIP together today

**Comment by jgribonvald** [comment]
My thought, having a web-component based on this api and servlet call (as choice) could be good. 
As use case if we integrate a portlet with an alternative maximized URL (and open the service on an other tab) the Web component integrate on the service will permit to maintain the session active and avoid to run without to see it the session timeout.

**Comment by bjagg** [comment]
@jgribonvald you can hit the user-info URL to refresh the session and, if wanted, pick up the session timeout value

**Comment by jgribonvald** [comment]
@bjagg, I already know it, my thougth was more on having a WC doing the job and like that we have only to add it into each app that we would need it ! Simple way so !
We already have a simple js that is doing the servlet refresh depending on user activity (it observes the mouse and keyboard event inside the page and refresh the session into the portal every X minutes - to avoid to refresh at each activity)
