### ISSUE TITLE
Add option to turn off JWT encryption

### ISSUE THREAD

**Issue by bjagg** [Jasig/uPortal#1743]
**Is your feature request related to a problem? Please describe.**
Development can be facilitated if JWT are not encrypted.

**Describe the solution you'd like**
Add a configuration option to turn off encryption of JWT (tokens) with a default of encrypt for backwards compatibility. This will include adding default configuration values, optionally signing JWT based on configuration, and documentation.

**Comment by ChristianMurphy** [comment]
@bjagg can you clarify what you mean by "encrypted" here?
uPortal uses [JWT](https://jwt.io/)s not [JWE](https://tools.ietf.org/html/rfc7516)s, JWTs are signed, but not encrypted.

**Comment by asgrant** [comment]
@ChristianMurphy I'm not sure if this is entirely true. Benito and I have been working on this issue, where the health checker is throwing an error stating the JWT is malformed (missing 2 periods). It's getting a hashed value instead.

https://github.com/Jasig/uPortal/blob/fb42cf9525325f6fea234bf9593910e0ef45d51f/uPortal-soffit/uPortal-soffit-core/src/main/java/org/apereo/portal/soffit/service/AbstractJwtService.java#L117

**Comment by bjagg** [comment]
I meant signing algorithm

**Comment by ChristianMurphy** [comment]
Gotcha, you are referring to https://tools.ietf.org/html/rfc7519#section-6

**Comment by bjagg** [comment]
For soffits, JWTs are encrypted. See https://github.com/Jasig/uPortal/blob/fb42cf9525325f6fea234bf9593910e0ef45d51f/uPortal-soffit/uPortal-soffit-core/src/main/java/org/apereo/portal/soffit/service/AbstractJwtService.java#L117
