### ISSUE TITLE
Invalid link to "transient" tab in sitemap

### ISSUE THREAD

**Issue by allanjackson** [Jasig/uPortal#1802]
On uPortal 5.7.1, sometimes the sitemap will display a link to the transient tab, "ft1" in the sitemap. I've had it show up in a couple different situations: after logging out (and loading our custom signout page) and after clearing the portal's cache.

The link shows the portlet you previously had focused as the text, but the url is servername/uPortal/f/ft1/normal/render.uP, which won't work.

I have a code fix I'm preparing to contribute.

**Comment by ChristianMurphy** [comment]
resolved in #1803
