### ISSUE TITLE
Search should return up to 50 unique results from Lucene

### ISSUE THREAD

**Issue by cbeach47** [Jasig/uPortal#1810]
**Describe the bug**
The code to search lucene only pulls the [first 50 results] (https://github.com/Jasig/uPortal/blob/master/uPortal-api/uPortal-api-rest/src/main/java/org/apereo/portal/rest/search/PortletsSearchStrategy.java#L89), and then removes duplicates.  When there is a lot of duplicates in the index, this causes less than 50 unique results to be returned, and not necessarily include the expected result.

**To Reproduce**
1. PortalInit a fresh clone of uP-start
2. Import several portlets that all would be returned in a search (for example, all contain 'course' in  the name)
3. Start uP and wait 3 minutes for the indexing to complete.
4. Confirm via the UI that the expected portlets are returned in the search
5. Wait 30 - 60 minutes for the indexing task to run several times (due to issue #1809, this causes a bunch of duplicates in the index).
6. Note via the UI that not all expected portlets are returned in the search (based on the ordering of the raw results)

**Expected behavior**
Up to 50 uniquely indexed documents (portlets) are returned.

**Platform:**
 - uPortal Version: 5.6.1
 - OS: Ubuntu
 - Browser Firefox

**Comment by cbeach47** [comment]
Also happens in uP 5.7.1

**Comment by ChristianMurphy** [comment]
@cbeach47 I assume this means results will be paginated?
Or would this limit the number of items added to the index?

**Comment by cbeach47** [comment]
Paginated results would be great, but that would require UI work. 

This ticket is just to ensure up to 50 unique results are returned to the user.  It could be argued that if #1809 was resolved this ticket wouldn't be needed.

**Comment by cbeach47** [comment]
Due to #1809 being resolved with #1863 , I don't see a value-add with this effort since the indexed documents (for now, portlets) should be unique.
