### ISSUE TITLE
:overlays:uPortal:dataInit FAILED

### ISSUE THREAD

**Issue by manojposwal** [Jasig/uPortal#1955]
After running the command ./gradlew portalInit
First time i face the problem in installation of of tomcat but it will work after changing the script but after that I face the problem of :overlays:uPortal:dataInit FAILED 
* Where:
Build file '/home/uportal/uPortal-start/overlays/uPortal/build.gradle' line: 253

* What went wrong:
Execution failed for task ':overlays:uPortal:dataInit'.
> Java returned: 1
![Screenshot from 2020-02-11 10-28-41](https://user-images.githubusercontent.com/58887226/74212235-4f38ba80-4cb9-11ea-8941-7c54fc5171d5.png)
[ktnxmraejt2la-console-log.txt](https://github.com/Jasig/uPortal/files/4184159/ktnxmraejt2la-console-log.txt)

**Comment by jonathanmtran** [comment]
With `HEAD` of uPortal-start, I didn't have any trouble with running `./gradlew portalInit`

What changes did you make to the script?
Do you have `.properties` files in `.gradle/tomcat/portal` ?

**Comment by manojposwal** [comment]
Dear sir
**When i face this problem 
**> Task :tomca**tInstall FAILED
Installing Tomcat servlet container version 8.5.40 to location .gradle/tomcat

> Task :overlays:basiclti-portlet:plutoAssemble
Processing archive basiclti-portlet.war into destination directory /home/tanuj/uPortal-start/overlays/basiclti-portlet/build/pluto with the Apache Pluto Assembler

FAILURE: Build failed with an exception.

* Where:
Script '/home/tanuj/uPortal-start/gradle/tasks/tomcat.gradle' line: 56

* What went wrong:
Execution failed for task ':tomcatInstall'.
> Problem expanding gzip /home/tanuj/uPortal-start/build/tmp/tomcat/tomcat-gunziped.tar (No such file or directory)**
then i made the change in the script that file i have attached the file.
after changing the script i face the problem that i have told you in previous comment.
will you please tell me the location of .**properties** file

**Comment by jonathanmtran** [comment]
I believe you're having troubles because you're trying to set this up using JDK 11. At the moment, JDK 11 is not supported (https://github.com/Jasig/uPortal/issues/1932)

You'll need to install JDK 8 (openjdk-8-jdk)

**Comment by manojposwal** [comment]
ok sir i will try by using java 8

**Comment by manojposwal** [comment]
Dear sir,
thanks for the help now i am able to install it.
When i restart my system i have to run the **./gradlew portalInit** because i am not able to open uportal on browser.
Will you please provide me the document for the beginner.

**Comment by ChristianMurphy** [comment]
https://github.com/Jasig/uPortal-start#readme is the getting started guide for uPortal-start

**Comment by jgribonvald** [comment]
As we can convince this problem was due to using a not supported JDK version. We will watch on for in a next uPortal version with JDK 11 compatibility.
