### ISSUE TITLE
Tab Groups broken in Respondr

### ISSUE THREAD

**Issue by bjagg** [Jasig/uPortal#2249]
**Describe the bug**
Tab Groups were a feature in Universality that was never successfully migrated to Respondr.

**To Reproduce**
1. Add `org.apereo.portal.layout.useTabGroups=true` to uPortal.properties
2. Add at least 2 tab groups to a user's layout. For example add 2 tab groups to the guest fragment layout
3. Confirm no tab groups are displayed

**Expected behavior**
Tab group bar above tabs should be displayed when there are more than 2 tab groups for a user.

**Screenshots**

**Comment by cbeach47** [comment]
Thanks for the fix @bjagg !
